### ISSUE TITLE
How to format Diagram？

### ISSUE THREAD

**Issue by xiongchaohu** [NorthwoodsSoftware/GoJS#113]
Now there is a problem. There are two modes: view mode and card mode can be switched, but the width and height of the node are inconsistent. For example, a new flow chart created in view mode will cause overlap when switching to card mode. Is there a way Can the node formatting in Diagram be automatically arranged without overlapping?
![image](https://user-images.githubusercontent.com/19620878/93413110-19a02380-f8d1-11ea-81ca-2c1669a7f81a.png)
![image](https://user-images.githubusercontent.com/19620878/93413268-70a5f880-f8d1-11ea-9a0b-d302c1a1edec.png)

**Comment by WalterNorthwoods** [comment]
The positioning of nodes, if not done explicitly by the user or your code, is the responsibility of the **Diagram.layout**.  You must not have assigned a layout, because normally changing the size of a node will invalidate the layout and cause it to be performed again at the end of the transaction.

So if you do not want an automatic layout by assigning **Diagram.layout**, you will need to move the nodes programmatically when you change "modes".

This is not a bug in GoJS but a question about how to use it which belongs in the forum, not in GitHub Issues.

Please do not use the GitHub issue tracker unless you are reporting a bug in GoJS,
not a problem in your code nor a question about how to do something or use something.

For help and support, please use the GoJS forum: https://forum.nwoods.com/c/gojs
