### ISSUE TITLE
Suggestion: Double tree layout alternateAngle

### ISSUE THREAD

**Issue by aszokalski** [NorthwoodsSoftware/GoJS#125]
I noticed that when using `DoubleTreeLayout` with `treeStyle: go.TreeLayout.StyleRootOnly` (and probably other styles) the angled tree started growing in the wrong direction. I quickly figured that setting `alternateAngle: 180` would fix it and it did. 

It's not really a bug but it's just an unexpected (or more like unwanted) behaviour you might want to look into. I suggest setting `alternateAngle` to the same value as 'angle' by default on the angled tree.

**Comment by WalterNorthwoods** [comment]
Setting **TreeLayout.treeStyle** means that you are explicitly asking for the use of the "alternate" **TreeVertex** values, instead of the regular default vertex property values.

If you do not set **treeStyle**, vertexes will inherit property values from their parent vertex.   https://gojs.net/latest/api/symbols/TreeLayout.html#static-StyleLayered

This lists the vertex properties that are inherited: https://gojs.net/latest/api/symbols/TreeLayout.html#rootDefaults
