### ISSUE TITLE
RotatingTool doesn't have specific typings

### ISSUE THREAD

**Issue by dominic-simplan** [NorthwoodsSoftware/GoJS#126]
In the go.d.ts file, the rotatingTool doesn't have specific typings, like the other tools. It extends the generic Tool class.
Could you add the type definitions of the RotationTool as well?

**Comment by WalterNorthwoods** [comment]
I was confused by this, until I recognized you meant the declared type of the **ToolManager.rotatingTool** property, not the definition of the **RotatingTool** class.  Thanks for pointing that out -- it will be fixed in the next release.

In the meantime, if you care, you can modify your own copy of the `go.d.ts` file.
