### ISSUE TITLE
makeUniqueKeyFunction is not called for first node of a template

### ISSUE THREAD

**Issue by FritzHerbers** [NorthwoodsSoftware/GoJS#20]
I opened a new issue as per your instructions. See  #19

Please test with the following sample:
[flowchart2.html.txt](https://github.com/NorthwoodsSoftware/GoJS/files/245251/flowchart2.html.txt)

The makeUniqueKeyFunction sets "key" fix to 1001 (only for this sample).
The palette does not have nodes with an attribute "key".
We load an initial empty model.

Add a node from the palette and save: key = -1
Add another node and save: key = 1001.

Why is the variable key for the first node not 1001?

The other question is not answered:
When adding to the model
```
"nodeKeyProperty": "uuid",
"linkKeyProperty": "uuid",
```
the function gets called, and the value is correct for uuid, but it is unclear why there is also a "key" saved, which is even not unique.
Why?

**Comment by simonsarris** [comment]
Generally, if you have two models that need to interact, you will want to set properties like `makeUniqueKeyFunction` and `nodeKeyProperty` on both of them, though there may be exceptions.

> Why is the variable key for the first node not 1001?

When adding new node data, GoJS does this:

> If the `data.key` does not exist, generate one, calling `makeUniqueKeyFunction`

> Else, the node data has a `data.key`, so use that key.
> > Unless the key is already in the map, then call `makeUniqueKeyFunction`

The first node to be copied over from the palette has a key assigned (by the palette) so the "Else" is true. It does not need to call `makeUniqueKeyFunction` to ensure uniqueness.

The second node to be copied over from the palette has the same key assigned, so "Else" is true again, but this time the "Unless" clause is also true. Duplicate keys are not acceptable, so it calls `makeUniqueKeyFunction` to ensure uniqueness.

These rules are important, because if you wanted to add new nodes (perhaps from a loaded source) that have keys defined already, you would not want to destroy that data.

You could also set the `makeUniqueKeyFunction` on the Palette's model, so that it doesn't use its default.


> the function gets called, and the value is correct for uuid, but it is unclear why there is also a "key" saved, which is even not unique.

Because you are copying data from myPalette.model, and the data looks like this:

`{text: "???", figure: "Diamond", key: -3, loc: "0 110"}`

So the data is copied over faithfully. Then, a key is added to that data, since it has none (since you declared the nodeKeyProperty to be "uuid" instead of "key")

GoJS will not destroy the "key" node data (or any node data), and the "key" was present in the palette, when you copy it to another model.

You could avoid that by setting `nodeKeyProperty` on both the Palette and the Diagram models.

**Comment by simonsarris** [comment]
Just so we are on the same page, when you are copying data from the palette, such as:

`{"text":"???", "figure":"Diamond", "key":-3, "loc":"-121.875 -131"}`

You *really* want to copy this instead:

`{"text":"???", "figure":"Diamond", "loc":"-121.875 -131"} // no key`

So that the Diagram Model is forced to make its own new key every time. Is that correct?

**Comment by WalterNorthwoods** [comment]
Another possibility is to leave the use of "key" as the **Model.nodeKeyProperty** in the **Palette**, and to continue to use "uuid" as the **Model.nodeKeyProperty** in the main **Diagram**, and to add this **DiagramEvent** listener:
```
            . . . ,
            "ExternalObjectsDropped": function(e) {
              e.diagram.nodes.each(function(n) {
                n.data.key = undefined;
              });
            },
```

**Comment by FritzHerbers** [comment]
Thx for the clarification and pointing to the existence of a generated key for the nodes in the palette diagram, which is copied over to the diagram.

I successfully used your last proposal. thx again.
