### ISSUE TITLE
Change the origin of the diagram's coordinate

### ISSUE THREAD

**Issue by tibdev78** [NorthwoodsSoftware/GoJS#201]
Hi
I'm a beginner in gojs and I've noticed that the origin of the diagram's coordinates is at the centre left and I'd like to change the origin to the bottom left.
For example, if I set the coordinate of a point to "0,0", I'd like it to start at the bottom and not in the centre, then if i set to "0,50" it goes up etc... .

Is it possible to change the default behaviour programmatically ?.

**Comment by simonsarris** [comment]
I cannot think of a reasonable way to change the coordinate system.

You could have your bindings convert so that (0, 50) translates to (0, -50) for GoJS, but that may lead to a lot of confusion later down the line.

For general support please use the forum in the future https://forum.nwoods.com/c/gojs/11
