### ISSUE TITLE
SuspendsRouting does not work - version 3.0.4

### ISSUE THREAD

**Issue by postulkam** [NorthwoodsSoftware/GoJS#215]
Hi, we used undocumented property `suspendsRouting`, but it doesn't exist in new version 3.0.4. Is there any other property that we can use instead?

Example with 3.0.4 version - https://jsfiddle.net/Mi_Po/8k1hcuzr/9/
Example with 2.3.16 version - https://jsfiddle.net/Mi_Po/oks6rx5e/57/

**Comment by simonsarris** [comment]
Thank you, we'll investigate and fix this.

**Comment by simonsarris** [comment]
`Link.suspendsRouting` is somewhat dangerous to use - you need to be very careful to reset it, and it may be better in your app if you created and removed a temporary Adornment on mouse hover instead of doing something that causes the Nodes to remeasure, broadly speaking.

However, we've decided to add `Link.suspendsRouting` back as an undocumented property in 3.0, starting with 3.0.6, which we will release probably next week. I will close this issue when that version is released.

**Comment by postulkam** [comment]
Thanks! I assumed that it can be dangerous, and we are really careful with it. However, we cannot use the Adornment because the user can decide whether they want to show the tooltip all the time, on hover, or when the object is selected.

**Comment by WalterNorthwoods** [comment]
We have released 3.0.7.
