### ISSUE TITLE
Trying to set undefined property ' ' on object

### ISSUE THREAD

**Issue by hadirsa** [NorthwoodsSoftware/GoJS#51]
Hi, 
I'm trying to run dynamicPorts example with reactjs. i've already run some gojs samples with react but i have problem with this one. i copy and paste the code from original example to my code. btw i used npm as package manager and webpack. here is part of my code that cause error.

```
this.state.myDiagram.linkTemplate =
    $(CustomLink,
        {
          routing: go.Link.AvoidsNodes,
          corner: 4,
          curve: go.Link.JumpGap,
          reshapable: true,
          resegmentable: true,
          relinkableFrom: true,
          relinkableTo: true
        },
        new go.Binding("points").makeTwoWay(),
        $(go.Shape, { stroke: "#2F4F4F", strokeWidth: 2 })
      );

function CustomLink() {
      go.Link.call(this);
    };

```
but when i run this i got 
```
Error: Trying to set undefined property "routing" on object: [object Object]
go.js:14:14
```
any idea abt this? 
Thanks

**Comment by WalterNorthwoods** [comment]
I think the problem is that you haven't correctly defined **CustomLink** as a subclass of **go.Link** before you use it to build a template.

So move the CustomLink constructor before you create the link template, and immediately after the constructor call `go.Diagram.inherit(CustomLink, go.Link);`.

Or define CustomLink as a proper class in ES6, `class CustomLink extends go.Link { . . .`
