### ISSUE TITLE
Items can only be moved when pressing hard on touch device (Microsoft Surface)

### ISSUE THREAD

**Issue by dominic-simplan** [NorthwoodsSoftware/GoJS#54]
In the latest version (1.8.11) items can only be moved via touch gesture on a Microsoft Surface Tablet when I press quite hard on the item (both palette and modelling area).

Until 1.8.2 and between 1.8.8 and 1.8.10 (e.g. https://gojs.net/1.8.10/samples/flowchart.html), I just needed to touch an item slightly to be able to move it around.
In 1.8.11 (e.g. https://gojs.net/1.8.11/samples/flowchart.html) and from 1.8.3 to 1.8.7, I need to press quite hard else the item gets only selected and the diagram is scrolled.

This seems to be related to #52: In versions where the drag into the diagram area works correctly, a hard press is needed.

**Comment by simonsarris** [comment]
Thanks, we'll take a look.

**Comment by simonsarris** [comment]
I do see what you mean. This is actually intentional.

For touch events, we have a delay in the dragging tool on starting it in order to allow easier panning. If you do not like this simply set the [DraggingTool.delay](https://gojs.net/latest/api/symbols/DraggingTool.html#delay) to 0:

```
    myDiagram = $(go.Diagram, "myDiagramDiv",
                  {
                    "draggingTool.delay": 0,
                     ...
```

-------

Some background:

The versions you are getting "immediate" behavior in are not using PointerEvents in IE, instead they're using IE's simulated Mouse events. These versions have some issues, the most obvious one being dragging between Diagrams (you can see that you can't drop from the Palette in 1.8.10's flowchart).

Chrome and Firefox don't emit simulated mouse events, instead they emit touch events, so they already work this way, with the delay.

**Comment by dominic-simplan** [comment]
I see, so it wasn't about pressing hard after all 😃 .
I have changed the delay to 20 and now it's what I've expected. Thanks also for the background information!
