### ISSUE TITLE
Can't use import syntax on extensions

### ISSUE THREAD

**Issue by ilazycat** [NorthwoodsSoftware/GoJS#65]
Hi there.

As described in the issue title, while I can use  `import go from gojs` statement to import gojs lib into VueJS component. I found it impossible to use something like `import Inspector from 'gojs/extensions/DataInspector'` to import the extension. After some investigation I found your extension code lake `export` statement. Simply add one line of `export default xxxxxx` will solve this problem.

For example I add `export default Inspector` to gojs/extensions/DataInspector.js file and then I can use `import Inspector from 'gojs/extensions/DataInspector'` to load the DataInspector extension without any problem.

**Comment by simonsarris** [comment]
We will not change the .js files to have an "export" statement because it will break the .js in most browsers. Of course, you can do so for your project.

For doing this in our `ExtensionsTS` directory automatically, we give an example of that in a project, here:

https://github.com/NorthwoodsSoftware/GoJS-projects/blob/master/angular-basic/src/app/diagram-editor/diagram-editor.component.ts#L4

See the last section of the TSconfig:

https://github.com/NorthwoodsSoftware/GoJS-projects/blob/master/angular-basic/tsconfig.json

The `extensions` directory files are meant to be included as plain JavaScript files. The `extensionsTS` directory files are similarly built to be included as UMD modules. If you want to use them as ES6 modules, you can, you just need to either rebuild the .js sources, or add some config to your project for them, like above.

**Comment by David102400** [comment]
above of link is 404,I also meet this question...

**Comment by simonsarris** [comment]
Sorry, the project was moved here: https://github.com/NorthwoodsSoftware/gojs-angular-basic
