### ISSUE TITLE
go.Panel TableColumn Not behaving as expected

### ISSUE THREAD

**Issue by Rakhmanov** [NorthwoodsSoftware/GoJS#87]
Hello dear team, recently ran in to uncharted territory with unexpected behavior. And I'm leaning toward it being a bug. 

There are a lot of examples of building Tables and using Panel type TableRow where user need to specify the column value to have it display properly.  However there is no TableColumn example, and one might assume setting panel to it and specifying row property will display columns one after another, and not on top of each other like it does it now.

**Expected:** Display columns one after another

**Actual:** Displayed one on top of the other in same column and row

**Example:**
https://codepen.io/Rakhmanov/pen/ZEEZqPo

**Comment by WalterNorthwoods** [comment]
Your node template has some contradictory definitions in it.

First, your Node is an "Auto" Panel and yet has only one element in it.  "Auto" Panels should have a border-like element (typically a Shape) that will surround the other element(s).

Second, the "Table" Panel only has one element in it, a "TableColumn" Panel.  So the "Table" will necessarily only have one column in it.  The defaultAlignment setting states that the "TableColumn" Panel should be aligned to the left, but since it is the only element in the "Table" Panel, the alignment really doesn't matter.

Third, the "TableColumn" Panel has its "itemArray" property data-bound to the "columnDefinitions" Array on the node data.  That's fine, but because the itemTemplate is a plain Panel (i.e. a "Position" Panel), it means that setting of row: 0 is redundant, because the default value for the row is zero.  That is why each Panel holding a TextBlock is in row zero.

Normally a "Table" Panel will have an itemTemplate that is either a "TableRow" Panel or a "TableColumn" Panel.

This template might be closer to what you are looking for:
```
  myDiagram.nodeTemplate =
    $(go.Node, "Auto",
      $(go.Shape, { fill: "cyan" }),  // the border Shape
      $(go.Panel, "Table",
        new go.Binding("itemArray", "columnDefinitions"),
        {
          itemTemplate:
            $(go.Panel, "TableColumn",
              $(go.TextBlock,
                {
                  margin: new go.Margin(2, 2, 0, 2),
                  font: "bold 10pt sans-serif",
                },
                new go.Binding("text")
              )
            )
        }
      )
    );
```
