### ISSUE TITLE
BPMN sample project does not work

### ISSUE THREAD

**Issue by kaashan** [NorthwoodsSoftware/GoJS#90]
I wanted to explore the BPMN sample present under projects folder. Launching the BPMN.html file in a browser does not load the editor to create a new workflow diagram. Same issue exists with the online demo as well [GoJS BPMN Editor](https://gojs.net/latest/projects/bpmn/BPMN.html#).

Examining the browser console shows up JS errors:
![image](https://user-images.githubusercontent.com/22172255/74582536-50345980-4fe3-11ea-8731-2481bfdb70e8.png)

Would like this error to be fixed so that we could explore a working demo of BPMN sample.

Thanks

**Comment by WalterNorthwoods** [comment]
I believe you can fix the problem in your copies of the files by making sure all **import** statements include ".js" as the file type.

In 2.1.8 all of the samples and extensions had switched to be explicit about the file type, to be consistent with import statements when importing ES6 modules.  Alas, we forgot to update the projects.  Apparently that causes the "go.js" library to be loaded twice, once by import "../release/go" and once by import "../release/go.js".  The second load clears out all of the additional figures defined in "../extensionsTS/Figures.js".

That seems like a bug in **import** to me, but that's how it is.  We can avoid the problem by being consistent when specifying the file types.  And apparently importing ES6 modules requires the file type, so that's not a problem in the future.

This is fixed in 2.1.9, which will come out next week (we're waiting for confirmation about an unrelated bug fix).  So you don't need to submit a pull request.  Thanks for reporting the problem.

**Comment by kaashan** [comment]
Thanks @WalterNorthwoods for your reply.

I was able to fix the JS errors by making below changes in local source files:

**In BPMNClasses.js**
change#1
replaced line#23 `define(["require", "exports", "../../release/go"], factory);`
with `define(["require", "exports", "../../release/go.js"], factory);`

change#2
replaced line#28 `var go = require("../../release/go");`
with `var go = require("../../release/go.js");`

**In BPMNScript.js**
change#1
replaced line#23 `define(["require", "exports", "../../extensionsTS/DrawCommandHandler", "../../extensionsTS/Figures", "../../release/go", "./BPMNClasses"], factory);`

with `define(["require", "exports", "../../extensionsTS/DrawCommandHandler.js", "../../extensionsTS/Figures.js", "../../release/go.js", "./BPMNClasses.js"], factory);`

change#2
replaced lines 28-31
`
var DrawCommandHandler_1 = require("../../extensionsTS/DrawCommandHandler");
require("../../extensionsTS/Figures");
var go = require("../../release/go");
var BPMNClasses_1 = require("./BPMNClasses");
`

with
`
var DrawCommandHandler_1 = require("../../extensionsTS/DrawCommandHandler.js");
require("../../extensionsTS/Figures.js");
var go = require("../../release/go.js");
var BPMNClasses_1 = require("./BPMNClasses.js");
`
